changed to_pandas to toPandas
dnanexus/OpenBio pull request #8
Opened 2021-07-30 06:22 UTC by djemec

given that retrieve_fields returns a spark dataframe and not a query proxy, to_pandas needs to be "toPandas" so tweaked that markdown

2021-07-30 06:23 UTC, djemec commented on dxdata/getting_started_with_dxdata.ipynb
> +  },
this is some items to help support a table of contents.  doesn't impact usage

2021-07-30 18:43 UTC, arunbhat commented
so to_koalas stays? kind of inconsistent.. but @keegankelsey  should review

2021-07-30 18:50 UTC, djemec commented
> so to_koalas stays? kind of inconsistent.. but @keegankelsey should review

@arunbhat  yeah, here's koalas function docs https://koalas.readthedocs.io/en/latest/reference/api/databricks.koalas.DataFrame.to_koalas.html

2021-08-05 04:27 UTC, djemec commented
> > so to_koalas stays? kind of inconsistent.. but @keegankelsey should review
> 
> @arunbhat yeah, here's koalas function docs https://koalas.readthedocs.io/en/latest/reference/api/databricks.koalas.DataFrame.to_koalas.html

I actually removed koalas from it and used native spark dataframes

2021-08-05 05:08 UTC, keegankelsey commented
I would change the initial description from
`...A Dataset object contains content that describes logical content in data and maps the logical data organization to the physical location of data stored in a database. It allows assign something a "Sample ID," a term with specific attributes, and easily store, retrieve, and use that term in a consistent manner. Below, we walk through highlights of dxdata specifically around initiating a spark cluster, pulling a datasets/cohort, exploring the data, and retrieving data to a dataframe`
to
`...A Dataset object maps the logical data model to physical storage, providing the means to retrieve data in a standardized manner. Below, we highlight aspects of dxdata. Specifically we show (a) how initiating a Spark cluster, (b) how to load and access metadata within Datasets and Cohorts, and (c) how to retrieve stored data as specified in Datasets and Cohorts.`

2021-08-05 05:11 UTC, keegankelsey commented
I can't access the Dataset, `record-G3814k006Fjgk5J74Kx3X1QF`. Will a public Dataset be provided? If not, access to specific fields used in this notebook may fail if the dataset is not aligned with content in the demo. I.E, not just any Dataset will work to load and run through the script.

This also means I can't fully test the notebook. Can you provide access to the dataset?

2021-08-05 05:15 UTC, keegankelsey commented
Same comment regarding access to the demo cohort and this line:

`cohort = dxdata.load_cohort(folder="/", name="controls")`

2021-08-05 05:27 UTC, djemec commented
> I would change the initial description from
> `...A Dataset object contains content that describes logical content in data and maps the logical data organization to the physical location of data stored in a database. It allows assign something a "Sample ID," a term with specific attributes, and easily store, retrieve, and use that term in a consistent manner. Below, we walk through highlights of dxdata specifically around initiating a spark cluster, pulling a datasets/cohort, exploring the data, and retrieving data to a dataframe`
> to
> `...A Dataset object maps the logical data model to physical storage, providing the means to retrieve data in a standardized manner. Below, we highlight aspects of dxdata. Specifically we show (a) how initiating a Spark cluster, (b) how to load and access metadata within Datasets and Cohorts, and (c) how to retrieve stored data as specified in Datasets and Cohorts.`

language updated

2021-08-05 05:33 UTC, djemec commented
> I can't access the Dataset, `record-G3814k006Fjgk5J74Kx3X1QF`. Will a public Dataset be provided? If not, access to specific fields used in this notebook may fail if the dataset is not aligned with content in the demo. I.E, not just any Dataset will work to load and run through the script.
> 
> This also means I can't fully test the notebook. Can you provide access to the dataset?

We do NOT plan on making the dataset publicly available.  George is making a slightly tweaked version for UKB that people should be able to use, but this is meant to be a starter where they replace the names and ids.
for testing use https://staging.dnanexus.com/panx/projects/G45g7fQ0yxky3kz04JF31bkK/data/

2021-08-05 05:34 UTC, djemec commented
> Same comment regarding access to the demo cohort and this line:
> 
> `cohort = dxdata.load_cohort(folder="/", name="controls")`

can use https://staging.dnanexus.com/panx/projects/G45g7fQ0yxky3kz04JF31bkK/data/

2021-08-05 16:14 UTC, keegankelsey commented
@djemec - everything looks good except the `to_koalas()` comment. See my notebook screen shots on PySpark and Koalas and use of `toPandas()`, `to_pandas()`, and `to_koalas()`.  Something like this workflow may be good to put in the notebook to avoid future confusion.  There are two  screenshots...just couldn't fit the full comment into a single screen. Message me if you want to chat  through this.
<img width="778" alt="Screen Shot 2021-08-05 at 9 09 58 AM" src="https://user-images.githubusercontent.com/7120192/128384410-81127114-4ed0-46ed-a838-a9c59d79ac4e.png">
<img width="711" alt="Screen Shot 2021-08-05 at 9 10 07 AM" src="https://user-images.githubusercontent.com/7120192/128384425-a96a0378-0c23-4c31-b1e7-98924ba053d7.png">

2021-08-05 16:15 UTC, keegankelsey requested changes
@djemec Please see my comments on `to_koalas()`. This should be updated in your notebook.

2021-08-05 17:00 UTC, keegankelsey approved these changes

2021-08-05 17:03 UTC, djemec commented
> @djemec Please see my comments on `to_koalas()`. This should be updated in your notebook.

Just to close out before merging, to_koalas and toPandas were added to the notebook

2021-08-05 17:03 UTC, merged